2024-04-03 17:36:40,042 INFO    MainThread:20776 [wandb_setup.py:_flush():76] Configure stats pid to 20776
2024-04-03 17:36:40,042 INFO    MainThread:20776 [wandb_setup.py:_flush():76] Loading settings from C:\Users\hugoa\.config\wandb\settings
2024-04-03 17:36:40,042 INFO    MainThread:20776 [wandb_setup.py:_flush():76] Loading settings from c:\Users\hugoa\H9\RL\GitHub Vrain\rl_levitation_control\rl_levitation_control\wandb\settings
2024-04-03 17:36:40,042 INFO    MainThread:20776 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-04-03 17:36:40,042 INFO    MainThread:20776 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-04-03 17:36:40,042 INFO    MainThread:20776 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-04-03 17:36:40,043 INFO    MainThread:20776 [wandb_init.py:_log_setup():506] Logging user logs to c:\Users\hugoa\H9\RL\GitHub Vrain\rl_levitation_control\rl_levitation_control\wandb\run-20240403_173640-gmfyfku3\logs\debug.log
2024-04-03 17:36:40,043 INFO    MainThread:20776 [wandb_init.py:_log_setup():507] Logging internal logs to c:\Users\hugoa\H9\RL\GitHub Vrain\rl_levitation_control\rl_levitation_control\wandb\run-20240403_173640-gmfyfku3\logs\debug-internal.log
2024-04-03 17:36:40,043 INFO    MainThread:20776 [wandb_init.py:init():546] calling init triggers
2024-04-03 17:36:40,043 INFO    MainThread:20776 [wandb_init.py:init():552] wandb.init called with sweep_config: {}
config: {}
2024-04-03 17:36:40,043 INFO    MainThread:20776 [wandb_init.py:init():602] starting backend
2024-04-03 17:36:40,043 INFO    MainThread:20776 [wandb_init.py:init():606] setting up manager
2024-04-03 17:36:40,046 INFO    MainThread:20776 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=spawn, using: spawn
2024-04-03 17:36:40,049 INFO    MainThread:20776 [wandb_init.py:init():613] backend started and connected
2024-04-03 17:36:40,052 INFO    MainThread:20776 [wandb_run.py:_label_probe_notebook():1204] probe notebook
2024-04-03 17:36:40,052 INFO    MainThread:20776 [wandb_run.py:_label_probe_notebook():1214] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-04-03 17:36:40,052 INFO    MainThread:20776 [wandb_init.py:init():701] updated telemetry
2024-04-03 17:36:40,205 INFO    MainThread:20776 [wandb_init.py:init():741] communicating run to backend with 60.0 second timeout
2024-04-03 17:37:40,243 ERROR   MainThread:20776 [wandb_init.py:init():755] backend process timed out, exiting...
encountered error: Error communicating with wandb process, exiting...
For more info see: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2024-04-03 17:37:40,252 ERROR   MainThread:20776 [wandb_init.py:init():1171] error
Traceback (most recent call last):
  File "C:\Users\hugoa\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wandb\sdk\wandb_init.py", line 1144, in init
    run = wi.init()
  File "C:\Users\hugoa\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wandb\sdk\wandb_init.py", line 773, in init
    raise error
wandb.errors.CommError: Error communicating with wandb process, exiting...
For more info see: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
